---
driver:
  name: ec2
  require_chef_omnibus: 12.16.42
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  security_group_ids:
    - sg-97e55ef2
  subnet_id: subnet-a792da8f
  interface: private
  iam_profile_name: test-ebs-attachment

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  log_level: debug

platforms:
- name: ubuntu-14.04
  run_list:
    - recipe[aws::ec2_hints]
    - recipe[storage::default]
  attributes:
    storage:
      ebs_volumes:
        vol1:
          device: /dev/xvde
          size: 2
          delete_on_termination: true

suites:
  - name: ebs
    driver:
      tags:
        Name: storage-ebs-ubuntu-1404
      instance_type: t2.medium
  - name: es
    driver:
      tags:
        Name: storage-es-ubuntu-1404
      instance_type: c3.xlarge
  - name: nvme
    driver:
      tags:
        Name: storage-nvme-ubuntu-1404
      instance_type: i3.large
