name             'storage'
maintainer       'EverTrue, Inc.'
maintainer_email 'eric.herot@evertrue.com'
license          'Apache v2.0'
description      'Installs/Configures storage'
long_description 'Installs/Configures storage'
version          '2.1.8'

depends 'ohai'
depends 'et_fog', '~> 1.1.1'
